#!/bin/sh
[ -z ${YATT_FZF+x} ] && YATT_FZF="fzf"
[ -z ${yatt_script_usage_prefix+x} ] && yatt_script_usage_prefix="\
Get id of yatt's record"
[ -z ${yatt_script_executable} ] && yatt_script_executable=$0

usage () {
  echo "\
$yatt_script_usage_prefix with preferred fuzzy finder.
By default, 'fzf' is used, but you can change it by setting \
YATT_FZF environment variable value.

USAGE:
    $yatt_script_executable [SUBCOMMAND]

SUBCOMMANDS:
    task        Handles tasks
    group       Handles groups
    interval    Handles intervals
    help        Prints this message
"
  exit 0
}

error () {
  echo "Error: invalid argument. Type \
'$yatt_script_executable help' to get list of possible commands."
  exit 1
}

[ -z ${1} ] && usage
[ "$1" != "help" ] || usage
echo $1 | grep -E '^task|interval|group$' > /dev/null || error

command=$(echo $1s | sed 's/groups/tasks -g/')

yatt -c list $command | $YATT_FZF | grep -o -E '^\[[[:digit:]]+' | grep --color=never -o -E '[[:digit:]]+'
