#!/bin/sh
export yatt_script_executable=$0
export yatt_script_usage_prefix="Deletes yatt's record"

id_cmd=${0%yatt-remove}yatt-id
id=$($id_cmd $1)

echo "$id" | grep -C 100 "$yatt_script_usage_prefix" && exit 0

[ -z "$id" ] && exit 0

entity=${1/group/task}

yatt delete -y $entity $id
