[package]
name = "yatt"
version = "0.1.0"
authors = ["dinAlt <dinalt2@gmail.com>"]
edition = "2018"
description = "Yet Another Task Tracker"

[dependencies]
clap = "2.33"
cli = { path = "cli" }

[workspace]
members = [
  "core",
  "cli",
  "storage/sqlite",
  "orm",
  "orm/orm_derive",
]

[profile.release]
lto = true # link time optimization - roughly halves the size of the exec
codegen-units = 1 # this removes a few hundred bytes from the final exec size
