[package]
name = "yatt"
version = "0.1.0"
authors = ["dinAlt <dinalt2@gmail.com>"]
edition = "2018"
description = "Yet Another Task Tracker"

[dependencies]
clap = "2.33"
cli = { version="0.1.0", path = "cli" }

[workspace]
members = [
  "core",
  "cli",
  "storage/sqlite",
  "orm",
  "orm/orm_derive",
]

[profile.release]
lto = true
codegen-units = 1
